export const DISPATCH_TYPE = {
  LOGIN: "USER_LOGIN",
  LOGOUT: "USER_LOGOUT",
  REGISTER: "USER_REGISTER",
  LOGIN_API: "USER_LOGIN_API",
  REGISTER_API: "USER_REGISTER_API",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  MODIFY_USER_2FA: "MODIFY_USER_2FA",
  MODIFY_AVATAR: "MODIFY_AVATAR",
  MODIFY_USER_DATA: "MODIFY_USER_DATA",
  MODIFY_USER_NAME: "MODIFY_USER_NAME",
  //session
  LOADING: "LOADING",
  CHANGE_LOCALE: "CHANGE_LOCALE",
  SHOW_CHATTING: "SHOW_CHATTING",
  SHOW_PANEL_SETTING: "SHOW_PANEL_SETTING",
  MOBILE_MENU_SHOWABLE: "MOBILE_MENU_SHOWABLE",

  //slot game
  ALL_GAME_UPDATE: "ALL_GAME_UPDATE",
  LATEST_GAME_UPDATE: "LATEST_GAME_UPDATE",
  HIGHEST_GAME_UPDATE: "HIGHEST_GAME_UPDATE",
  MY_GAME_UPDATE: "MY_GAME_UPDATE",
};
